make_beverage:
  name: Prepare beverage
  description: Prepares beverages from the list of available beverages
  target:
    entity:
      domain: delonghi_primadonna
      supported_features:
        - delonghi_primadonna.BeverageEntityFeature.    MAKE_BEVERAGE = 1


  fields:
    beverage:
      name: Beverage
      description: Beverage to prepare
      required: true
      default: "none"
      selector:
        select:
          translation_key: "fan_speed"
          options:
            - "none"
            - "steam"
            - "long"
            - "coffee"
            - "dopio"
            - "hot_water"
            - "espresso"
            - "americano"
            - "espresso2"